Update fdo to 21.08
flathub/cc.arduino.arduinoide pull request #33
Opened 2021-09-30 12:06 UTC by A6GibKm

2021-10-06 18:49 UTC, MartinIIOT requested changes
Try update openJDK to 11 and make changes in lines 63, 64 too.

2021-10-06 18:49 UTC, MartinIIOT commented on cc.arduino.arduinoide.json
>          "org.freedesktop.Sdk.Extension.openjdk8"
```suggestion
        "org.freedesktop.Sdk.Extension.openjdk11"
```

2021-10-11 05:38 UTC, MartinIIOT commented
OpenJDK 8 is available for 21.08 runtime:
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/issues/13#issuecomment-939047080

2021-10-11 17:16 UTC, A6GibKm commented
bot, build

2021-10-11 17:52 UTC, merged